name: Github Actions

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build the Docker image
        run: |
          chmod -Rf 755 *
          . secrets.rc
          ./builder.sh latest-chromium build
          docker images
        
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: flywithu/ubuntu-vnc-xfce-g3-ko 
          
      -
        name: Push
        run: |
          docker push flywithu/ubuntu-vnc-xfce-g3-ko:latest-chromium
 
